version: '2'
services:
  eureka-server:
    image: anapsix/alpine-java:8_jdk
    volumes:
      - ./eureka-server/target/eureka-server.jar:/app.jar
      - ./eureka-server/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    ports:
      - "8761:8761"
  eureka-client:
    image: anapsix/alpine-java:8_jdk
    volumes:
      - ./eureka-client/target/eureka-client.jar:/app.jar
      - ./eureka-client/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    depends_on:
      - eureka-server
    links:
      - eureka-server:eureka-server
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
  feign-client:
    image: anapsix/alpine-java:8_jdk
    volumes:
      - ./feign-client/target/feign-client.jar:/app.jar
      - ./feign-client/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - eureka-client
    links:
      - eureka-server:eureka-server
      - eureka-client:eureka-client
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
  hystrix-dashboard:
    image: anapsix/alpine-java:8_jdk
    volumes:
      - ./hystrix-dashboard/target/hystrix-dashboard.jar:/app.jar
      - ./hystrix-dashboard/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    links:
      - eureka-server:eureka-server
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
  turbine:
    image: anapsix/alpine-java:8_jdk
    volumes:
      - ./turbine/target/turbine.jar:/app.jar
      - ./turbine/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    links:
      - eureka-server:eureka-server
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka