spring:
  application:
    name: spring-cloud-eureka-client

server:
  port: 0

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health

info:
  app:
    name: Eureka Client
    description: Greetings service
    version: @project.version@