spring:
  application:
    name: spring-cloud-eureka-feign-client

server:
  port: 8080

info:
  app:
    name: Eureka Feign
    description: Feign services
    version: @project.version@

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health